# Generated by Django 2.1.3 on 2018-11-25 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testform', '0002_auto_20181111_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='resident',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
