# Generated by Django 2.1.3 on 2019-03-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testform', '0003_auto_20181125_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=50)),
                ('merch_name', models.CharField(max_length=70)),
                ('merch_size', models.CharField(max_length=10)),
                ('merch_cost', models.IntegerField()),
            ],
        )
    ]
