# Generated by Django 2.1.3 on 2019-03-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('price', models.IntegerField()),
                ('avatar_url', models.ImageField(upload_to='merch_photos')),
                ('creared_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=225)),
                ('content', models.TextField()),
                ('news_picture_url', models.ImageField(upload_to='news_photos')),
                ('creared_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
