# Generated by Django 2.1.3 on 2019-05-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='resident',
            name='number',
            field=models.CharField(max_length=30),
        ),
    ]
