# Generated by Django 2.2.1 on 2019-05-29 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190528_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='merch_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='merch_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='merch_size',
        ),
        migrations.AddField(
            model_name='order',
            name='merch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='app.Merch'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='merch',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='header',
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
