# Generated by Django 2.2.1 on 2019-05-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190529_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='created_at',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='resident',
            name='created_at',
            field=models.CharField(max_length=15),
        ),
    ]
