# Generated by Django 2.2.2 on 2019-06-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190529_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='resident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
