# Generated by Django 2.1.7 on 2019-08-16 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_resident_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='merch',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Odessa', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='getFromAtom',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='merch_cost',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='merch_name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='merch_size',
            field=models.CharField(default=None, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='np_mail',
            field=models.CharField(default=None, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='resident',
            name='birthday',
            field=models.CharField(
                default=datetime.date(2019, 8, 16), max_length=10),
        ),
    ]
