# Generated by Django 2.1.10 on 2019-08-17 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190817_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='getFromAtom',
            new_name='is_get_from_atom',
        ),
    ]
