# Generated by Django 2.1.10 on 2019-08-17 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190817_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='created_at',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='resident',
            old_name='created_at',
            new_name='created_time',
        ),
        migrations.AddField(
            model_name='mentor',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
