# Generated by Django 2.2.5 on 2019-11-22 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191101_1246'),
        ('app', '0009_auto_20191107_2024'),
    ]

    operations = [
    ]
