# Generated by Django 2.2.5 on 2019-11-23 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_merge_20191122_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='birthday',
            field=models.CharField(default=datetime.date(2019, 11, 23), max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='merch',
            unique_together=set(),
        ),
    ]
